<?php displays('header.phtml'); ?>
<div class="container">
<h1><?php echo $this->title; ?></h1>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->content; ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->content; ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->content; ?>
        </div>
    </div>
</div>
<?php displays('footer.phtml'); ?>
