<!DOCTYPE html>
<html lang="<?php echo container()->getLanguage()->getLanguage(); ?>">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta name="author" content="Thin framework" />
        <title><?php echo $this->title; ?></title>

        <!-- Bootstrap core CSS -->
        <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" />
        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet" />
        <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css" media="screen" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:400,300,700,900,600|Oswald:400,300,700,900,600|Passion+One:400,300,700,900,600|Questrial:400,300,700,900,600&amp;subset=latin,latin-ext" />

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="<?php $this->asset('js/ie8-responsive-file-warning.js'); ?>"></script>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <script>
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', '']);
          _gaq.push(['_trackPageview']);
          (function() {
            var ga = document.createElement('script'); ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>
        <style>
            *,label, input, button, select, textarea {font-family: Questrial,Oswald; font-size: 18px;}
        </style>
    </head>
    <body>
