<?php $this->partial('partials/header/classic.phtml'); ?>
<div class="container">
<h1><?php echo $this->title; ?></h1>
    <div class="row">
        <?php echo $this->content; ?>
        <blockquote>
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
            ipsum Lorem ipsum lorem ipsum lorem<hr />
        </blockquote>
    </div>
</div>
<?php $this->partial('partials/footer/classic.phtml'); ?>
