<?php includes('partials/header/classic.phtml'); ?>
<div class="container">
    <div class="row">
        <div class="span12">
            <?php echo Thin\Html\Helper::display(cms_info('block', 'content', $this->page)); ?>
        </div>
    </div>
    <div class="row">
        <div class="span3">
            <?php echo Thin\Html\Helper::display(cms_info('block', 'col1', $this->page)); ?>
        </div>
        <div class="span3">
            <?php echo Thin\Html\Helper::display(cms_info('block', 'col2', $this->page)); ?>
        </div>
        <div class="span3">
            <?php echo Thin\Html\Helper::display(cms_info('block', 'col3', $this->page)); ?>
        </div>
        <div class="span3">
            <?php echo Thin\Html\Helper::display(cms_info('block', 'col4', $this->page)); ?>
        </div>
    </div>
</div>
<?php includes('partials/footer/classic.phtml'); ?>
