<?php includes('partials/header/classic.phtml'); ?>
<style>
    .liList {
        font-weight: 800;
        color: #2C3E50;
        text-transform: uppercase;
    }
</style>
<!-- Main Content -->
    <div id="content" role="main">
        <p style="height: 40px;"></p>
        <div class="section">
            <div class="container">
                <div class="page-header">
                    <h1>
                        Tableau de Bord
                    </h1>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <ul class="nav nav-list">
                        <?php $i = 0; foreach ($this->types as $type): ?>
                        <?php if (ake($type, \Thin\Data::$_fields)):
                        $i++; ?>
                        <li class="dropdown span3 pull-right">
                            <a class="dropdown-toggle liList pull-right" data-toggle="dropdown" href="#" onclick="return false;">
                                <i class="icon-cogs"></i> <i><?php echo ucfirst(\Thin\Inflector::lower(\Thin\Html\Helper::adminPlural($type))); ?></i>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="/backadmin/item/<?php echo \Thin\Html\Helper::display($type); ?>"><i class="icon-list"></i> Liste</a></li>
                                <li><a href="/backadmin/item_add/<?php echo \Thin\Html\Helper::display($type); ?>"><i class="icon-plus"></i> Ajouter</a></li>
                                <li><a href="/backadmin/import-<?php echo \Thin\Html\Helper::display($type); ?>"><i class="icon-folder-open"></i> Importer</a></li>
                            </ul>
                        </li>
                        <?php if (0 === $i % 4): ?></ul></div></div><div class="row-fluid"><div class="span12"><ul><?php endif; ?>
                        <?php endif; ?>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php includes('partials/footer/classic.phtml'); ?>
