<?php includes('partials/header/classic.phtml'); ?>
<div class="container">
    <div class="row">
        <div class="span12">
            <?php echo Thin\Html\Helper::display(cms_info('block', 'content', $this->page)); ?>
            <h1><?php echo Thin\Html\Helper::display(cms_info('meta', 'h1', $this->page)); ?></h1>
            <h2><?php echo Thin\Html\Helper::display(cms_info('meta', 'h2', $this->page)); ?></h2>
            <h3><?php echo Thin\Html\Helper::display(cms_info('meta', 'h3', $this->page)); ?></h3>
            <h4><?php echo Thin\Html\Helper::display(cms_info('meta', 'h4', $this->page)); ?></h4>
            <h5><?php echo Thin\Html\Helper::display(cms_info('meta', 'h5', $this->page)); ?></h5>
            <h6><?php echo Thin\Html\Helper::display(cms_info('meta', 'h6', $this->page)); ?></h6>
        </div>
    </div>
</div>
<?php includes('partials/footer/classic.phtml'); ?>
