<?php includes('partials/header/classic.phtml'); ?>
<div class="container">
    <div class="row">
        <div class="span3">
            <?php echo Thin\Html\Helper::display(cms_info('block', 'left', $this->page)); ?>
        </div>
        <div class="span9">
            <?php echo Thin\Html\Helper::display(cms_info('block', 'content', $this->page)); ?>
        </div>
    </div>
</div>
<?php includes('partials/footer/classic.phtml'); ?>
