        <?php echo cms_info('block', 'footer', $this->page); ?>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="//cdn.cityzend.com/u/45880241/cdn/js/hover.js"></script>
        <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
        <script>
        $(document).ready(function() {
            $('.openHover').dropdownHover().dropdown();
            $('[rel=tooltip-bottom]').tooltip({
                placement: 'bottom'
            });
            $('[rel=tooltip-top]').tooltip({
                placement: 'bottom'
            });
            $('[rel=tooltip-left]').tooltip({
                placement: 'left'
            });
            $('[rel=tooltip-right]').tooltip({
                placement: 'right'
            });
        });
        </script>
    </body>
</html>
