<?php includes('partials/header/classic.phtml'); ?>
<!-- Main Content -->
    <div id="content" role="main">
        <section class="section">
            <div class="container">
                <div class="row-fluid">
                    <div class="comments-form">
                        <h3 class="comment-form">
                            Mettre à jour une page
                        </h3>
                        <form class="form-horizontal" action="<?php urlsite(); ?>cms/edit/<?php echo $this->id; ?>" method="post">
                            <fieldset>
                                <div class="control-group">
                                    <label class="control-label" for="title">Titre</label>
                                    <div class="controls">
                                        <input class="input-xxlarge" value="<?php echo $this->page->getTitle(); ?>" name="title" id="title" type="text" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="Url">Url</label>
                                    <div class="controls">
                                        <input class="input-xxlarge" value="<?php echo $this->page->getRoute(); ?>" name="route" id="route" type="text" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="language">Langue</label>
                                    <div class="controls">
                                        <input value="<?php echo $this->page->getLanguage(); ?>" class="input-small" name="language" id="language" type="text" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="description">Description</label>
                                    <div class="controls">
                                        <textarea class="input-xxlarge" name="description" id="description" rows="6"><?php echo $this->page->getDescription(); ?></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="keywords">Mots clés</label>
                                    <div class="controls">
                                        <textarea class="input-xxlarge" name="keywords" id="keywords" rows="6"><?php echo $this->page->getKeywords(); ?></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="content_page"></label>
                                    <div class="controls">
                                        <textarea class="ckeditor input-xxlarge" name="content_page" id="content_page" rows="6"><?php echo $this->page->getContentPage(); ?></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <div class="controls">
                                        <button class="btn btn-primary" type="submit">Mettre à jour</button>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<?php includes('partials/footer/classic.phtml'); ?>
