<?php includes('partials/header/classic.phtml'); ?>
    <div id="content" role="main">
        <section class="section">
            <div class="container">
                <div class="row-fluid">
                    <div class="span1">&nbsp;</div>
                    <div class="widget span10">
                        <div class="widget-header clearfix">
                            <h3><i class="icon-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo \Thin\Html\Helper::display($this->title); ?></h3>
                        </div>
    <div class="widget-body">
            <form id="formEditCrud" class="form-horizontal" action="<?php echo URLSITE . 'admin/edit/' . request()->getEntity() . '/' . request()->getTable() . '/' . request()->getId(); ?>" method="post" enctype="multipart/form-data">
            <?php foreach($this->form as $element): ?>
                <?php echo $element; ?>
            <?php endforeach; ?>
                <div class="control-group">
                    <div class="controls">
                        <button type="submit" class="btn btn-success" name="submit">Mettre à jour</button> &nbsp;
                        <button type="reset" class="btn btn-warning" name="reset">Annuler</button>
                    </div>
                </div>
            </form>
            <p />
            <div>
                <button id="backListCrud" type="button" class="btn btn-info" onclick="document.location.href = '<?php echo URLSITE . 'admin/list/' . request()->getEntity() . '/' . request()->getTable(); ?>';"><i class="icon-list icon-white"></i> Retour à la liste</button>
            </div>
        </div>
    </div>
</div>
</div>
<?php includes('partials/footer/classic.phtml'); ?>
