    </div>
    <footer>
        <div class="ctner">
            <img id="footDog" src="<?php urlsite(); ?>assets/web/foot-dog.png" alt="Pilouf" height="325" width="225">
            <a href="http://www.soluxor.ca/dev/www/Site2/1" id="footerLogo"><img src="<?php urlsite(); ?>assets/web/pilouf-logo-footer.png" alt="Pilouf" height="110" width="152"></a>
            <div id="footNav">
                <ul>
                <li class="first"><a href="http://www.soluxor.ca/dev/www/Site2/a-propos.html" title="À propos">À propos</a></li>
                <li class="active"><a href="<?php urlsite(); ?>produits-pilouf.html" title="Produits">Produits</a></li>
                <li><a href="http://www.soluxor.ca/dev/www/Site2/pilouf-entretien.html" title="Entretien">Entretien</a></li>
                <li><a href="http://www.soluxor.ca/dev/www/Site2/promesse-pilouf.html" title="Promesse Pilouf">Promesse Pilouf</a></li>
                <li><a href="http://www.soluxor.ca/dev/www/Site2/temoignages-client/" title="Témoignages client">Témoignages</a><ul><li class="first"><a href="http://www.soluxor.ca/dev/www/Site2/temoignages-client/faq.html" title="FAQ">FAQ</a></li>
                </ul></li>
                <li class="last"><a href="http://www.soluxor.ca/dev/www/Site2/contactez-nous.html" title="Contactez-nous">Contactez-nous</a></li>
                </ul>
            </div>
        </div>
    </footer>

</div>


</body></html>
