<!DOCTYPE html>
<html lang="fr">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta charset="utf-8" />
    <title>Produits - Pilouf</title>
    <link rel="stylesheet" type="text/css" href="<?php urlsite(); ?>assets/web/injected.css" />
    <meta name="Description" content="" />
    <meta name="Keywords" content="" />
    <meta name="Designer" content="Carbure Design" />
    <meta name="rating" content="General" />
    <meta name="Robots" content="INDEX,FOLLOW" />
    <meta name="googlebot" content="index,follow,snippet" />
    <meta name="geo.country" content="ca" />
    <meta name="geo.region" content="ca-qc" />
    <meta name="geo.placename" content="montréal" />
    <link href="<?php urlsite(); ?>assets/web/css.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="<?php urlsite(); ?>assets/web/style.css" />
<!--[if lte IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
    <script type="text/javascript" src="<?php urlsite(); ?>assets/web/jsapi"></script>
    <script src="<?php urlsite(); ?>assets/web/jquery_003.js"></script>
<!-- Anything Slider -->
<script src="<?php urlsite(); ?>assets/web/jquery_002.js"></script>
<script src="<?php urlsite(); ?>assets/web/swfobject.js"></script>
<link rel="stylesheet" href="<?php urlsite(); ?>assets/web/anythingslider.css" />
<script src="<?php urlsite(); ?>assets/web/jquery.js"></script>
<link rel="stylesheet" href="<?php urlsite(); ?>assets/web/theme-mini-light.css" />

<link rel="stylesheet" href="<?php urlsite(); ?>assets/web/style.css" />
<style>.upper{text-transform: uppercase;}</style>
<!-- Required -->
<script type="text/javascript">
$(function(){
 $('#slider')
   .anythingSlider({
        expand          : true,
        theme           : "mini-light",
        autoPlay        : true,
        width           : 975,
        delay           : 7000,
        resumeDelay     : 15000,
        animationTime   : 600,
        startPanel      : 1,
        hashTags        : false
   })
});
</script>
</head>

<!-- page content -->
<div id="conteneur">

   <header id="head">
    <div class="ctner">
        <a href="/" id="homeLogo"><img src="<?php urlsite(); ?>assets/web/pilouf-coussins-canin.png" alt="Pilouf - logo" height="161" width="209"></a>
           <!-- <a href="<?php urlsite(); ?>cart.html" id="shopCart">Panier d'achat</a> -->
        <div id="icoNav">
            <a href="/partenaires.html">Partenaires</a>
            <a href="/politique-dachat.html">Politique d’achat</a>

<a href="<?php urlsite(); ?>en/products.html">en</a>

            <a href="https://www.facebook.com/piloufinc" target="_blank"><img src="<?php urlsite(); ?>assets/web/facebook_icon_15.png" alt="facebook" height="15" width="7"></a>
        </div>
        <nav>
            <ul><li class="first"><a href="/a-propos.html" title="À propos">À propos</a></li>
<li class="active"><a href="<?php urlsite(); ?>produits-pilouf.html" title="Produits">Produits</a></li>
<li><a href="/pilouf-entretien.html" title="Entretien">Entretien</a></li>
<li><a href="/promesse-pilouf.html" title="Promesse Pilouf">Promesse Pilouf</a></li>
<li><a href="/temoignages-client/" title="Témoignages client">Témoignages</a></li>
<li class="last"><a href="/contactez-nous.html" title="Contactez-nous">Contactez-nous</a></li>
</ul>
        </nav>

     </div>
   </header>
   <!-- slidder -->
            <div id="sliderCnt">
                    <div style="width: 975px; height: 430px;" class="anythingSlider anythingSlider-mini-light activeSlider"><div style="width: 100%; height: 100%;" class="anythingWindow"><div style="width: 6825px; left: -3900px;" class="anythingBase horizontal" id="slider"><div style="width: 975px; height: 430px;" class="slide-slice cloned panel">
    <p class="slidder_title">&nbsp;</p><p class="slidder_title">&nbsp;</p>
<a name="" disabled="disabled" class="btnLink" href="#">Voir tous les produits</a> <img class="slide-image" src="<?php urlsite(); ?>assets/web/dog-slider-5.png" alt="Osez le style Optez pour un Pilouf !" height="427" width="870">
</div>
                      <div style="width: 975px; height: 430px;" class="slide-slice panel">
    <p class="slidder_title"><span>Osez le</span> <span>style</span> <span>Optez pour un Pilouf !</span></p>
<a class="btnLink" href="#">Voir tous les produits</a> <img class="slide-image" src="<?php urlsite(); ?>assets/web/dog-slider-8.png" alt="Osez le style Optez pour un Pilouf !" height="427" width="600">
</div>
<div style="width: 975px; height: 430px;" class="slide-slice panel">
    <p class="slidder_title"><span>Osez le</span> <span>style</span> <span>Optez pour un Pilouf !</span></p>
<a class="btnLink" href="#">Voir tous les produits</a> <img class="slide-image" src="<?php urlsite(); ?>assets/web/dog-slider-6.png" alt="Osez le style Optez pour un Pilouf !" height="427" width="600">
</div>
<div style="width: 975px; height: 430px;" class="slide-slice panel">
    <p class="slidder_title"><span>Osez le</span> <span>style</span> <span>Optez pour un Pilouf !</span></p>
<a class="btnLink" href="#">Voir tous les produits</a> <img class="slide-image" src="<?php urlsite(); ?>assets/web/dog-slider-7.png" alt="Osez le style Optez pour un Pilouf !" height="427" width="600">
</div>
<div style="width: 975px; height: 430px;" class="slide-slice panel activePage">
    <p class="slidder_title"><span>Osez le</span> <span>style</span> <span>Optez pour un Pilouf !</span></p>
<a class="btnLink" href="#">Voir tous les produits</a> <img class="slide-image" src="<?php urlsite(); ?>assets/web/dog-slider-4.png" alt="Osez le style Optez pour un Pilouf !" height="427" width="600">
</div>
<div style="width: 975px; height: 430px;" class="slide-slice panel">
    <p class="slidder_title">&nbsp;</p><p class="slidder_title">&nbsp;</p>
<a class="btnLink" href="#">Voir tous les produits</a> <img class="slide-image" src="<?php urlsite(); ?>assets/web/dog-slider-5.png" alt="Osez le style Optez pour un Pilouf !" height="427" width="870">
</div>
                    <div style="width: 975px; height: 430px;" class="slide-slice cloned panel">
    <p class="slidder_title"><span>Osez le</span> <span>style</span> <span>Optez pour un Pilouf !</span></p>
<a name="" disabled="disabled" class="btnLink" href="#">Voir tous les produits</a> <img class="slide-image" src="<?php urlsite(); ?>assets/web/dog-slider-8.png" alt="Osez le style Optez pour un Pilouf !" height="427" width="600">
</div></div></div><div class="anythingControls"><ul class="thumbNav"><li class="first"><a class="panel1 tooltip" title="1" href="#"><span>1</span></a></li><li><a class="panel2 tooltip" title="2" href="#"><span>2</span></a></li><li><a class="panel3 tooltip" title="3" href="#"><span>3</span></a></li><li><a class="panel4 tooltip cur" title="4" href="#"><span>4</span></a></li><li class="last"><a class="panel5 tooltip" title="5" href="#"><span>5</span></a></li></ul><a title="Stop" href="#" class="start-stop tooltip playing"><span>Stop</span></a></div><span class="arrow back"><a href="#"><span>«</span></a></span><span class="arrow forward"><a href="#"><span>»</span></a></span></div>
            </div> <!-- fin slidder -->
   <section id="headSection">
       <div class="ctner">
<!-- featured -->
            <div id="featured">
                <ul>
                    <li>
                        <a href="#" class="titleFeatured"><strong>Coussin</strong>Ultra-résistant</a>
                        <a href="#"><img src="<?php urlsite(); ?>assets/web/dog-1.png" alt="" height="215" width="213"></a>
                    </li>
                    <li>
                        <a href="#" class="titleFeatured"><strong>Foulard</strong>Tendance</a>
                        <a href="#"><img src="<?php urlsite(); ?>assets/web/dog-2.png" alt="" height="215" width="213"></a>
                    </li>
                    <li>
                        <a href="#" class="titleFeatured"><strong>Nouveau produit</strong>Disponible sous peu</a>
                        <a href="#"><img src="<?php urlsite(); ?>assets/web/dog-3.png" alt="" height="215" width="213"></a>
                    </li>
                </ul>
            </div>
       </div>
   </section>

<div class="ctner" id="bodyWrapper">
       <aside id="bodySideProdL">
       <!-- Sidebar here ########### recherche avancée ######## -->
          <div class="advSearch">
                <p class="sTitle">recherche avancée</p>
                <form method="post" id="advSearchForm" action="<?php urlsite(); ?>prodSearch.html#products">
                    <input type="hidden" name="field" id="field" value="" />
                    <input type="hidden" name="field_value" id="fieldValue" value="" />
                </form>
                <ul>
                    <li><input type="radio" name="prodList" id="allprod" value="allprod" onclick="makeSearch(this.name, this.value);" <?php if($this->session->getField() == 'prodList' && $this->session->getFieldValue() == 'allprod'): ?>checked="checked"<?php endif; ?> /><label for="allprod">TOUS LES PRODUITS</label></li>
                    <?php
                        $objs = \Thin\Data::query('etat', '', 0, 0, 'name', 'ASC');
                        if (count($objs)):
                            foreach ($objs as $obj):
                    ?>
                    <li><input type="radio" name="prodList" id="<?php echo $obj->getId(); ?>" value="<?php echo $obj->getId(); ?>" onclick="makeSearch(this.name, this.value);" <?php if($this->session->getField() == 'prodList' && $this->session->getFieldValue() == $obj->getId()): ?>checked="checked"<?php endif; ?> /><label for="<?php echo $obj->getId(); ?>"><span class="upper"><?php echo \Thin\Html\Helper::display($obj->getName()); ?></span></label></li>
                <?php endforeach; endif; ?>
                </ul>

                <p class="advSstitle">Catégorie</p>
                <ul>

                    <?php
                        $objs = \Thin\Data::query('categorie', '', 0, 0, 'name', 'ASC');
                        if (count($objs)):
                            foreach ($objs as $obj):
                    ?>
                    <li><input type="radio" name="catProdList" id="<?php echo $obj->getId(); ?>" value="<?php echo $obj->getId(); ?>" onclick="makeSearch(this.name, this.value);" <?php if($this->session->getField() == 'catProdList' && $this->session->getFieldValue() == $obj->getId()): ?>checked="checked"<?php endif; ?> /><label for="<?php echo $obj->getId(); ?>"><span class="upper"><?php echo \Thin\Html\Helper::display($obj->getName()); ?></span></label></li>
                    <?php endforeach; endif; ?>
                </ul>

                <!-- p class="advSstitle">Couleurs</p>
                <ul class="advScolor">
                    <li><input type="radio" name="colorProdList" id="B38866" value="B38866" /><label for="B38866">#B38866</label></li>
                    <li><input type="radio" name="colorProdList" id="B38867" value="B38867" /><label for="B38867">#B38867</label></li>
                    <li><input type="radio" name="colorProdList" id="B38868" value="B38868" /><label for="B38868">#B38868</label></li>
                    <li><input type="radio" name="colorProdList" id="B38869" value="B38869" /><label for="B38869">#B38869</label></li>
                    <li><input type="radio" name="colorProdList" id="B38860" value="B38860" /><label for="B38860">#B38860</label></li>
                    <li><input type="radio" name="colorProdList" id="B38861" value="B38861" /><label for="B38861">#B38861</label></li>
                    <li><input type="radio" name="colorProdList" id="B38862" value="B38862" /><label for="B38862">#B38862</label></li>
                    <li><input type="radio" name="colorProdList" id="B38863" value="B38863" /><label for="B38863">#B38863</label></li>
                    <li><input type="radio" name="colorProdList" id="B38864" value="B38864" /><label for="B38864">#B38864</label></li>
                </ul -->

                <p class="advSstitle">Collection</p>
                <ul>
                    <?php
                        $objs = \Thin\Data::query('collection', '', 0, 0, 'name', 'ASC');
                        if (count($objs)):
                            foreach ($objs as $obj):
                    ?>
                    <li><input type="radio" name="collProdList" id="<?php echo $obj->getId(); ?>" value="<?php echo $obj->getId(); ?>" onclick="makeSearch(this.name, this.value);" <?php if($this->session->getField() == 'collProdList' && $this->session->getFieldValue() == $obj->getId()): ?>checked="checked"<?php endif; ?> /><label for="<?php echo $obj->getId(); ?>"><?php echo \Thin\Html\Helper::display($obj->getName()); ?></label></li>
                <?php endforeach; endif; ?>
                </ul>
            </div>
       <!-- Sidebar here ########### recherche avance END ######## -->
       </aside>
       <script type="text/javascript">
       function makeSearch(field, fieldValue)
       {
            document.getElementById('field').value = field;
            document.getElementById('fieldValue').value = fieldValue;
            if (0 < document.getElementById('field').value.length && 0 < document.getElementById('fieldValue').value.length) {
                document.getElementById('advSearchForm').submit();
            }
       }
       </script>
