<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"/>
        <meta name="author" content="Gérald Plusquellec - me@geraldplusquellec.me" />
        <link href="<?php urlsite(); ?>assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet" />
        <link href="<?php urlsite(); ?>assets/css/icomoon.css" rel="stylesheet" />
        <link href="<?php urlsite(); ?>assets/css/glyphicons.css" rel="stylesheet" />
        <link href="<?php urlsite(); ?>assets/css/halflings.css" rel="stylesheet" />
        <link href="<?php urlsite(); ?>assets/css/entypo.css" rel="stylesheet" />
        <link href="<?php urlsite(); ?>assets/css/fonts/brandon/brandon.css" rel="stylesheet" />
        <link  href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/css/base/minified/jquery-ui.min.css" rel="stylesheet" />
        <link href="<?php urlsite(); ?>assets/css/style.css?v=<?php echo time(); ?>" rel="stylesheet" />
        <?php if($this->isIE === true): ?><link href="<?php urlsite(); ?>assets/css/ie.css?v=<?php echo time(); ?>" rel="stylesheet" />     <html class="no-js lt-ie9"><?php endif; ?>
        <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src='//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js'></script>
        <?php if ('fr' == getLanguage()): ?><script src="<?php urlsite(); ?>assets/js/jquery.ui.datepicker-fr.js"></script><?php endif; ?>
        <script src="<?php urlsite(); ?>assets/js/respond.js"></script>
        <script src="<?php urlsite(); ?>assets/js/bootstrap.min.js"></script>
        <script src="<?php urlsite(); ?>assets/js/ph.js"></script>
        <script src="<?php urlsite(); ?>assets/js/css3.js"></script>
        <script src="<?php urlsite(); ?>assets/js/bkg.js"></script>
        <script src="<?php urlsite(); ?>assets/js/web.js"></script>
        <link href="<?php urlsite(); ?>assets/img/icocc.png" rel="shortcut icon" />
        <script>
            function setAppLanguage(lng)
            {
                document.getElementById('app_language').value = lng;
                document.getElementById('setLanguage').action = document.URL;
                document.getElementById('setLanguage').submit();
            }
        </script>
        <!--[if lt IE 9]>
        <style>

          .hero {
    min-height: 590px;
    margin-top: -170px;
  }
    .secondHeader {
        position: relative;
        top: 15px;
    }

    #homeForm input, #homeForm textarea, #homeForm select {
        min-height: 22px;
    }

    #homeForm select {
        min-height: 22px;
    }
    </style>
        <!-- <![endif] -->
        <title>Champagne &amp; Confetti - <?php echo $this->title; ?></title>
    </head>
    <body>
        <?php includes('partials/header/head.phtml'); ?>
            <?php includes('partials/header/menu.phtml'); ?>
            <!--[if lt IE 9]><div class="clear"></div><!-- <![endif] -->
            <?php if ('fr' == getLanguage()): ?>
            <header class="hero fcontainer_12">
                <div class="secondHeader ccenter">
                    <br />
                    <span class="logoHeader">Champagne &amp; Confetti</span>
                    <div class="ccenter ccUp ccBold ccTitle">votre mariage, simplifié!</div>
                    <div class="sep2"></div>
                    <div class="ccenter info2">Planifiez votre mariage en un endroit, découvrez nos fournisseurs de choix et profitez des escomptes que les fournisseurs ont accordés aux membres de <span class="ccEm">Champagne &amp; Confetti</span>.</div>
                    <div class="sep"></div>
                    <?php if (false === $this->IsIE): ?>
                    <div class="ccenter info2"><a href="<?php urlsite(); ?>member" class="btn btn-large">devenir membre</a></div>
                    <?php else: ?>
                    <div class="ccenter info2"><button onclick="webJS.go('<?php urlsite(); ?>member');" class="btnLargeMin ccUp inputSize">devenir membre</button></div>
                    <?php endif; ?>
                </div>
            </header>
            <?php endif; ?>
            <?php if ('uk' == getLanguage()): ?>
            <header class="hero fcontainer_12">
                <div class="secondHeader ccenter">
                    <br />
                    <span class="logoHeader">Champagne &amp; Confetti</span>
                    <div class="ccenter ccUp ccBold ccTitle">Your wedding, simplified!</div>
                    <div class="sep2"></div>
                    <div class="ccenter info2">Plan your wedding in a one stop shop, discover our choice of vendors and enjoy discounts that providers granted to <span class="ccEm">Champagne &amp; Confetti</span> members.</div>
                    <div class="sep"></div>
                    <?php if (false === $this->IsIE): ?>
                    <div class="ccenter info2"><a href="<?php urlsite(); ?>member" class="btn btn-large">become a member</a></div>
                    <?php else: ?>
                    <div class="ccenter info2"><button onclick="webJS.go('<?php urlsite(); ?>member');" class="btnLargeMin ccUp inputSize">become a member</button></div>
                    <?php endif; ?>
                </div>
            </header>
            <?php endif; ?>
