<?php $this->data = \Thin\Data::order($this->type, $this->data, array('category', 'place'), array('ASC', 'ASC')); ?>
<?php includes('partials/header/classic.phtml'); ?>
<!-- Main Content -->
    <div id="content" role="main">
        <section class="section">
            <div class="container">
                <div class="page-header">
                    <h1>
                        Liste des fournisseurs
                    </h1>
                </div>
                <div class="row-fluid">
                    <div class="span1"></div>
                    <div class="span11">
                        <p>
                            <a href="<?php urlsite(); ?>backadmin/item_add/<?php echo $this->type; ?>"><button id="addCrudItem" type="button" class="btn btn-success">
                                <i class="icon-plus"></i> Ajouter un fournisseur
                            </button></a>
                        </p>
                    </div>
                    <?php if (!count($this->data)): ?>
                    <div class="span1"></div>
                    <div class="span8 alert alert-block alert-info fade in">
                        <button data-dismiss="alert" class="close" type="button">×</button>
                        <h4 class="alert-heading">Aucun fournisseur</h4>
                        <p>Il n'y a pour le moment aucun fournisseur à afficher.</p>
                    </div>
                    <div class="span3"></div>
                    <?php else: ?>
                    <?php \ThinHelper\Html::listTable($this->type, $this->data, array('name' => array('label' => 'nom'), 'place' => array('label' => 'ordre'), 'category' => array('label' => 'Catégorie', 'content' => array('getValueEntity', 'categorie', 'name')), 'city' => array('label' => 'Ville'))); ?>
                    <?php endif; ?>
                </div>
            </div>
        </section>
    </div>
<?php includes('partials/footer/classic.phtml'); ?>
