<?php includes('partials/header/classic.phtml'); ?>
    <div id="content" role="main">
        <section class="section">
            <div class="container">
                <div class="row-fluid">
                    <div class="span1">&nbsp;</div>
                    <div class="widget span10">
                        <div class="widget-header clearfix">
                            <h3><i class="icon-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo \Thin\Html\Helper::display($this->title); ?></h3>
                        </div>
    <div class="widget-body">
            <?php foreach ($this->data as $field => $value): ?>
            <legend><?php echo $field; ?></legend>
            <pre class="prettyprint"><?php echo \Thin\Html\Helper::display($value); ?></pre>
            <?php endforeach; ?>
            <p />
            <div>
                <button id="printCrud" type="button" class="btn btn-inverse" onclick="window.print();"><i class="icon-print icon-white"></i> Imprimer</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button id="backListCrud" type="button" class="btn btn-info" onclick="document.location.href = '<?php echo URLSITE . 'admin/list/' . request()->getEntity() . '/' . request()->getTable(); ?>';"><i class="icon-list icon-white"></i> Retour à la liste</button>
            </div>
        </div>
    </div>
</div>
</div>
<?php includes('partials/footer/classic.phtml'); ?>
