    <!-- Page Footer -->
        <footer class="section" id="footer" role="contentinfo">
            <div class="container">
                <div class="row-fluid">
                    <div class="span12 pull-center" style='font-size: 80%;'>&copy; 1996 - <?php echo date('Y'); ?> GP</div>
                </div>
            </div>
        </footer>
        <script>
        $(document).ready(function() {
            $('.openHover').dropdownHover().dropdown();
        });
    </script>
    </div>
    </body>
</html>
