<?php includes('partials/header/classic.phtml'); ?>
<!-- Main Content -->
    <div id="content" role="main">
        <section class="section">
            <div class="container">
                <div class="row-fluid">
                    <div class="comments-form">
                        <h3 class="comment-form">
                            Se connecter
                        </h3>
                        <form action="<?php urlsite(); ?>cms/login" method="post" class="form-inline">
                            <input type="text" name="username" id="username" class="input" placeholder="Identifiant" />
                            <input type="password" name="password" id="password" class="input" placeholder="Mot de passe" />
                            <button type="submit" class="btn btn-primary">Connexion</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<?php includes('partials/footer/classic.phtml'); ?>
