                    <?php \Thin\Blog::disqus(); ?>
                    <aside class="span3 sidebar">
                        <div class="sidebar-widget">
                            <h2 class="sidebar-header"><i class="icon-comments-alt"></i> Billets récents</h2>
                            <ul class="unstyled">
                                <?php for ($i = date('Y') ; $i > date('Y') - 3 ; $i--): ?>
                                <?php $articles = \Thin\Blog::getByYear($i); ?>
                                <?php if(count($articles)): ?>
                                <li>
                                    <h4>
                                        <a href="<?php urlsite(); ?>year/<?php echo $i; ?>"><?php echo $i; ?></a>
                                    </h4>
                                    <?php if (date('Y') == $i): ?>
                                    <ul class="unstyled">
                                    <?php for ($m = 1 ; $m < 13 ; $m++): ?>
                                        <?php $articles = \Thin\Blog::getByMonth($m, $i); ?>
                                        <?php if(count($articles)): ?>
                                        <li>
                                            <h4><a href="<?php urlsite(); ?>month/<?php echo $m; ?>-<?php echo $i; ?>"><?php echo \Thin\Blog::getMonthName($m); ?></a></h4>
                                            <ul>
                                                <?php $a = 0; foreach ($articles as $article): $a++; ?>
                                                    <li>
                                                        <h5><a style="color: #555;" href="<?php urlsite(); ?>post/<?php echo $article->getCategory(); ?>/<?php echo $article->getId(); ?>/<?php echo \Thin\Inflector::slugify($article->getTitle()); ?>"><?php echo $article->getTitle(); ?>
                                                            <span class="label" style="padding: 4px;"><?php echo date('d', $article->dateCreate); ?> <?php echo \Thin\Blog::getMonthName(date('n', $article->dateCreate)); ?></span></a></h5>
                                                    </li>
                                                <?php if (3 <= $a): ?><li><a href="<?php urlsite(); ?>month/<?php echo $m; ?>-<?php echo $i; ?>">Voir davantage&hellip;</li><?php break; endif; ?>
                                                <?php endforeach; ?>
                                            <ul>
                                        </li>
                                        <?php endif; ?>
                                    <?php endfor; ?>
                                    </ul>
                                    <?php endif; ?>
                                </li>
                                <?php endif; ?>
                                <?php endfor; ?>
                            </ul>
                        </div>
                        <div class="sidebar-widget">
                            <h2 class="sidebar-header"><i class="icon-tags"></i> Catégories</h2>
                            <ul class="unstyled">
                                <?php $categories = \Thin\Blog::getCategories(); ?>
                                <?php foreach ($categories as $category => $number): ?>
                                <li>
                                    <h4>
                                        <a href="<?php urlsite(); ?>category/<?php echo $category; ?>"><?php echo \thin\Inflector::upper($category); ?> (<?php echo $number; ?>)</a>
                                    </h4>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </aside>
