<?php displays('header.phtml'); ?>
<div class="inner">
    <div class="section">
        <div class="row12">
            <h1><?php echo $this->title; ?></h1>
        </div>
    </div>
    <div class="section">
        <div class="row4">
            <?php echo $this->content; ?>
        </div>
        <div class="row4">
            <?php echo $this->content; ?>
        </div>
        <div class="row4">
            <?php echo $this->content; ?>
        </div>
    </div>
</div>
<?php displays('footer.phtml'); ?>
