<?php includes('partials/header/classic.phtml'); ?>
<!-- Main Content -->
    <div id="content" role="main">
        <section class="section">
            <div class="container">
                <div class="row-fluid">
                    <div class="comments-form">
                        <h3 class="comment-form">
                            Ajouter une page
                        </h3>
                        <form class="form-horizontal" action="<?php urlsite(); ?>cms/add" method="post">
                            <fieldset>
                                <div class="control-group">
                                    <label class="control-label" for="title">Titre</label>
                                    <div class="controls">
                                        <input class="input-xxlarge" name="title" id="title" type="text" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="Url">Url</label>
                                    <div class="controls">
                                        <input class="input-xxlarge" name="route" id="route" type="text" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="language">Langue</label>
                                    <div class="controls">
                                        <input value="fr" class="input-small" name="language" id="language" type="text" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="description">Description</label>
                                    <div class="controls">
                                        <textarea class="input-xxlarge" name="description" id="description" rows="6"></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="keywords">Mots clés</label>
                                    <div class="controls">
                                        <textarea class="input-xxlarge" name="keywords" id="keywords" rows="6"></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="content_page"></label>
                                    <div class="controls">
                                        <textarea class="span10" name="content_page" id="content_page" cols="50" rows="6"></textarea>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <div class="controls">
                                        <button class="btn btn-primary" type="submit">Ajouter</button>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script type="text/javascript">
//<![CDATA[
  bkLib.onDomLoaded(function() {
        new nicEditor({fullPanel : true}).panelInstance('content_page');
  });
  //]]>
  </script>
<?php includes('partials/footer/classic.phtml'); ?>
