<?php includes('partials/header/classic.phtml'); ?>
<div class="ctner" id="bodyWrapper">
    <section id="bodySectionL">
        <article>
            <p>Panier</p>
        <?php if(1 > $this->cart->count()): ?>
            Le panier est vide.
        <?php else: ?>
            <?php $i = 0; foreach($this->cart->content() as $rowId => $row): ?>
            <?php if($i < 1): ?><ul><?php endif; ?>
            <li>
                <p>Article : <?php echo $row->getName(); ?></p>
                <p>Prix unitaire : <?php echo $row->getPrice(); ?> $ CAD</p>
                <p>Quantité : <?php echo $row->getQty(); ?> <a href="<?php urlsite(); ?>cart-add-<?php echo $rowId; ?>.html">+</a> <a href="<?php urlsite(); ?>cart-del-<?php echo $rowId; ?>.html">-</a></p>
                <p>Sous-total : <?php echo $row->getSubtotal(); ?> $ CAD</p>
            </li>
            <?php $i++; endforeach; ?>
            <?php if($i > 0): ?>
              </ul>
              <p><strong>TOTAL : <?php echo $this->cart->total(); ?> $ CAD</strong></p>
            <?php endif; ?>
            <p><a href="<?php urlsite(); ?>buy.html">Finaliser la commande</a></p>
            <?php endif; ?>
       </article>
    </section>
</div>
<?php includes('partials/footer/classic.phtml'); ?>
