<?php includes('partials/header/product.phtml'); ?>

<form method="post" id="advSearchForm" action="<?php urlsite(); ?>prodSearch.html#products">
    <input type="hidden" name="field" id="field" value="" />
    <input type="hidden" name="field_value" id="fieldValue" value="" />
</form>
<script type="text/javascript">
    function showThumb(newSrc)
    {
        document.getElementById('mainProductImage').src = newSrc;
    }

   function makeSearch(field, fieldValue)
   {
        document.getElementById('field').value = field;
        document.getElementById('fieldValue').value = fieldValue;
        if (0 < document.getElementById('field').value.length && 0 < document.getElementById('fieldValue').value.length) {
            document.getElementById('advSearchForm').submit();
        }
   }
</script>
<div class="ctner" id="bodyWrapper">
       <section id="bodySectionProduit">
       <article>
   <!-- <div class="prodNav"><a href="#"><</a><a href="#">></a></div> -->
<h1><?php echo \Thin\Html\Helper::display($this->product->getCategorie()->getName()); ?></h1>
<p class="crumbs"><a href="#" onclick="makeSearch('prodList', 'allprod'); return false;">Produits</a> > <a href="#" onclick="makeSearch('catProdList', '<?php echo $this->product->getCategorie()->getId(); ?>'); return false;"><?php echo \Thin\Html\Helper::display($this->product->getCategorie()->getName()); ?></a> > <a href="#" class="last"><?php echo \Thin\Html\Helper::display($this->product->getName()); ?></a></p>


<div id="imageProdSide">
    <img id="mainProductImage" src="<?php echo $this->product->image_1; ?>" alt="<?php echo \Thin\Html\Helper::display($this->product->getCategorie()->getName()); ?>" width="468"  />

    <div id="sharedBtn">
        <a target="_facebook" href="<?php echo facebook(array(
                'image'     => $this->product->image_1,
                'url'       => getUrl(),
                'title'     => \Thin\Html\Helper::display($this->product->getName()),
                'summary'   => \Thin\Html\Helper::display($this->product->getDescriptionFr()),
            )); ?>"><img src="<?php urlsite(); ?>assets/web/images/prods/fb-share.png" alt="facebook" width="24" height="24" /></a>
        <a target="_twitter" href="<?php echo twitter(array(
                'original_referer'  => getUrl(),
                'url'               => getUrl(),
                'related'           => 'Pilouf',
                'via'               => 'Pilouf',
                'text'              => \Thin\Html\Helper::display($this->product->getName()),
            )); ?>"><img src="<?php urlsite(); ?>assets/web/images/prods/t-share.png" alt="twitter" width="24" height="24" /></a>
        <!--a href="#"><img src="<?php urlsite(); ?>assets/web/images/prods/g-share.png" alt="google +" width="24" height="24" /></a>
        <a href="#"><img src="<?php urlsite(); ?>assets/web/images/prods/in-share.png" alt="Linked In" width="24" height="24" /></a>-->
    </div>

    <div id="moreImages"> <!-- ################################## MAX NUMBER OF IMAGE 3 -->
        <?php if(!empty($this->product->image_1)): ?>
        <a href="#" onclick="showThumb('<?php echo $this->product->image_1; ?>'); return false;"><img src="<?php echo $this->product->image_1; ?>" alt="<?php echo \Thin\Html\Helper::display($this->product->getCategorie()->getName()); ?>" width="92" height="92" /></a>
        <?php endif; ?>
        <?php if(!empty($this->product->image_2)): ?>
        <a href="#" onclick="showThumb('<?php echo $this->product->image_2; ?>'); return false;"><img src="<?php echo $this->product->image_2; ?>" alt="<?php echo \Thin\Html\Helper::display($this->product->getCategorie()->getName()); ?>" width="92" height="92" /></a>
        <?php endif; ?>
        <?php if(!empty($this->product->image_3)): ?>
        <a href="#" onclick="showThumb('<?php echo $this->product->image_3; ?>'); return false;"><img src="<?php echo $this->product->image_3; ?>" alt="<?php echo \Thin\Html\Helper::display($this->product->getCategorie()->getName()); ?>" width="92" height="92" /></a>
        <?php endif; ?>
    </div>
    <?php if(!empty($this->product->cross_sell_1) || !empty($this->product->cross_sell_2)): ?>
    <div id="accessoires">
        <p class="title">Produits assortis</p>
        <?php if(!empty($this->product->cross_sell_1)):
            $product = \Thin\Data::getById('produit', $this->product->cross_sell_1);
        ?>
        <a href="<?php urlsite(); ?>produit_<?php echo $product->getId(); ?>_<?php echo \Thin\Html\Helper::display(\Thin\Inflector::slugify($product->getName())); ?>.html"><img src="<?php echo $product->image_1; ?>" alt="<?php echo \Thin\Html\Helper::display($product->getName()); ?>" width="92" height="92" /></a>
        <?php endif; ?>
        <?php if(!empty($this->product->cross_sell_2)):
            $product = \Thin\Data::getById('produit', $this->product->cross_sell_2);
        ?>
        <a href="<?php urlsite(); ?>produit_<?php echo $product->getId(); ?>_<?php echo \Thin\Html\Helper::display(\Thin\Inflector::slugify($product->getName())); ?>.html"><img src="<?php echo $product->image_1; ?>" alt="<?php echo \Thin\Html\Helper::display($product->getName()); ?>" width="92" height="92" /></a>
        <?php endif; ?>
    </div>
    <?php endif; ?>

</div>


<div id="textProdMain">
    <h2><?php echo \Thin\Html\Helper::display($this->product->getName()); ?></h2>
    <p><?php echo \Thin\Html\Helper::bbdecode($this->product->getDescriptionFr()); ?></p>

	<p style="font-style: italic">Pour information sur les dimensions, prix et commander un produit, <a href="/contactez-nous.html">contactez-nous</a></p>
	<p style="font-style:italic; color: red;">* Achat en ligne, bientôt disponible.</p>

     <?php $collection = $this->product->getCollection(); if(!empty($collection)): ?>

   <div class="item"><p><span>Collection :</span><span><?php echo \Thin\Html\Helper::display($collection->getName()); ?></span></p>
    </div>
    <?php endif; ?><!--
    <div class="item">
        <p><span>Couleurs :</span><span>
                                    <img class="prodCouleur" src="<?php urlsite(); ?>assets/web/images/prods/ico-couleur.png" alt="Nom de la couleur" width="26" height="14" />Gris #456543 <br />
                                    <img class="prodCouleur" src="<?php urlsite(); ?>assets/web/images/prods/ico-couleur.png" alt="Nom de la couleur" width="26" height="14" />Vert #456543 <br />
                                    <img class="prodCouleur" src="<?php urlsite(); ?>assets/web/images/prods/ico-couleur.png" alt="Nom de la couleur" width="26" height="14" />Bleu #456543</span></p>
    </div>

    <div class="item">
        <p><span>Dimensions :</span><span> <strong>M</strong>    (44.5'' x 27.5" x 8 ")</span></p>
    </div>

    <div class="item">
        <p><span>Quantité :</span><span><input type="text" name="qty" id="qty" /></span></p>
    </div>

    <div class="item">
        <a class="btnLink basket" href="<?php urlsite(); ?>cart_<?php echo $this->product->getId(); ?>_<?php echo \Thin\Html\Helper::display(\Thin\Inflector::slugify($this->product->getName())); ?>.html">Ajouter au panier</a>
    </div>

   <div class="otherBaskItems">
        <p><a href="#"><img src="<?php urlsite(); ?>assets/web/images/prods/ico-caisse.png" alt="" width="21" height="34" />Passer à la caisse</a></p>
        <p><a href="#"><img src="<?php urlsite(); ?>assets/web/images/prods/ico-print.png" alt="" width="23" height="33" />Imprimer la fiche</a></p>
        <p><a href="#"><img src="<?php urlsite(); ?>assets/web/images/prods/ico-shipping.png" alt="" width="31" height="18" />Voir les garanties et les conditions de livraison</a></p>
    </div>
	-->
</div>

<!-- ###################################### CONTENU CENTRAL ############################################# -->
       </article>
   </section>
</div>
<?php includes('partials/footer/classic.phtml'); ?>
