<?php includes('partials/header/classic.phtml'); ?>
<style>
    .formDiv .label {
        float:left;
        width: 35%;
        text-align: right;
        padding: 5px;
    }
    .formDiv .field {
        float:left;
        width: 35%;
        text-align: left;
        padding: 5px;
    }
</style>
<div class="ctner" id="bodyWrapper">
    <section id="bodySectionL">
        <article>
            <p>Créer son compte</p>
            <p>
                <form action="<?php urlsite(); ?>register.html" method="post" id="registerForm">
                <div class="formDiv">
                    <div class="label">
                        Civilité
                    </div>
                    <div class="field">
                        <select required id="genre" name="genre">
                            <option>Choisir</option>
                            <option value="1">Monsieur</option>
                            <option value="2">Madame</option>
                            <option value="3">Mademoiselle</option>
                        </select>
                    </div>
                    <div class="label">
                        Nom
                    </div>
                    <div class="field">
                        <input type="text" required name="name" id="name" />
                    </div>
                    <div class="label">
                        Prénom
                    </div>
                    <div class="field">
                        <input type="text" required name="firstname" id="firstname" />
                    </div>
                    <div class="label">
                        Numéro de téléphone
                    </div>
                    <div class="field">
                        <input type="text" name="phone" id="phone" />
                    </div>
                    <div class="label">
                        Numéro de cellulaire
                    </div>
                    <div class="field">
                        <input type="text" name="mobile" id="mobile" />
                    </div>
                    <div class="label">
                        Courriel
                    </div>
                    <div class="field">
                        <input type="email" required name="email" id="email" />
                    </div>
                    <div class="label">
                        Mot de passe
                    </div>
                    <div class="field">
                        <input type="password" required name="password" id="password" />
                    </div>
                    <div class="label">
                        Adresse
                    </div>
                    <div class="field">
                        <textarea required name="address" id="address"></textarea>
                    </div>
                    <div class="label">
                        Code postal
                    </div>
                    <div class="field">
                        <input type="text" required name="zip" id="zip" />
                    </div>
                    <div class="label">
                        Ville
                    </div>
                    <div class="field">
                        <input type="text" required name="city" id="city" />
                    </div>
                    <div class="label">
                        &nbsp;
                    </div>
                    <div class="field">
                        <input type="submit" value="OK" />
                    </div>
                </div>
                </form>
            </p>
       </article>
    </section>
</div>
<?php includes('partials/footer/classic.phtml'); ?>
