<?php includes('partials/header/classic.phtml'); ?>
<!-- Main Content -->
    <div id="content" role="main" class="page">
        <div class="section">
            <div class="container">
                <div class="page-header">
                    <h1>
                        Tableau de Bord
                    </h1>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <?php $i = 0; foreach ($this->types as $type): ?>
                        <?php if (ake($type, \Thin\Data::$_fields) && ake($type, \Thin\Data::$_rights)):
                        $i++; ?>
                        <div class="btn-group span3">
                            <button class="btn btn-large btn-success dropdown-toggle openHover" data-toggle="dropdown"><?php echo ucfirst(\Thin\Inflector::lower(\Thin\Html\Helper::adminPlural($type))); ?> <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <?php if(can($type, 'list')): ?><li><a href="<?php urlsite(); ?>backadmin/item/<?php echo \Thin\Html\Helper::display($type); ?>"><i class="icon-list"></i> Liste</a></li><?php endif; ?>
                                <?php if(can($type, 'add')): ?><li><a href="<?php urlsite(); ?>backadmin/item_add/<?php echo \Thin\Html\Helper::display($type); ?>"><i class="icon-plus"></i> Ajouter</a></li><?php endif; ?>
                                <?php if(can($type, 'import')): ?><li><a href="<?php urlsite(); ?>backadmin/import-<?php echo \Thin\Html\Helper::display($type); ?>"><i class="icon-folder-open"></i> Importer</a></li><?php endif; ?>
                                <?php if(can($type, 'empty_cache')): ?><li class="divider"></li>
                                <li><a href="<?php urlsite(); ?>backadmin/emptyCache-<?php echo \Thin\Html\Helper::display($type); ?>"><i class="icon-trash"></i> Vider le cache</a></li><?php endif; ?>
                            </ul>
                        </div>
                        <?php if (0 === $i % 4): ?></div></div><hr /><div class="row-fluid"><div class="span12"><?php endif; ?>
                        <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
                <hr />
            </div>
        </div>
    </div>
<?php includes('partials/footer/classic.phtml'); ?>
