<?php includes('partials/header/classic.phtml'); ?>
<!-- Main Content -->
    <div id="content" role="main" class="page">
        <div class="section">
            <div class="container">
                <div class="page-header">
                    <h1>
                        Tableau de Bord
                    </h1>
                </div>
                <div class="row">
                    <div class="widget span9">
                        <div class="widget-header">
                            <h2>Arborescence du site</h2>
                        </div>
                        <div class="widget-body text-left">
                        <?php $pages = Thin\Cms::getParents(); ?>
                        <?php if (count($pages)): ?>
                            <ul>
                                <?php foreach ($pages as $page): ?>
                                <?php $children = Thin\Cms::getChildren($page); ?>
                                <li>
                                    <?php if(Thin\Cms::__($page->getUrl()) == 'home'): ?>
                                        <i class="fa fa-home"></i>
                                    <?php endif; ?>
                                    <?php if(Thin\Cms::__($page->getUrl()) == 'contact'): ?>
                                        <i class="fa fa-envelope"></i>
                                    <?php endif; ?>
                                    <?php echo $page->getName(); ?>
                                    <?php if (count($children )): ?>
                                        <ul>
                                        <?php foreach ($children as $child): ?>
                                        <?php $littleChildren = Thin\Cms::getChildren($child); ?>
                                            <li>
                                                <?php echo $child->getName(); ?>
                                                <?php if (count($littleChildren )): ?>
                                                    <ul>
                                                        <?php foreach ($littleChildren as $littleChild): ?>
                                                            <li>
                                                                <?php echo $littleChild->getName(); ?>
                                                            </li>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                <?php endif; ?>
                                            </li>
                                        <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php includes('partials/footer/classic.phtml'); ?>
