<?php includes('partials/header/classic.phtml'); $fields = \Thin\Data::$_fields[$this->type];?>
<script>
    CURLANG = WBBLANG['fr'] || WBBLANG['en'] || CURLANG;
</script>
<!-- Main Content -->
    <div id="content" role="main" class="page">
        <section class="section">
            <div class="container">
                <div class="page-header">
                    <h1>
                        Mettre à jour <?php echo \Thin\Html\Helper::adminSingular($this->type); ?>
                    </h1>
                </div>
                <div class="row-fluid">
                    <div class="span1"></div>
                    <div class="span11">
                        <form class="form-horizontal" action="<?php urlsite(); ?>backadmin/item_edit/<?php echo $this->type; ?>/<?php echo $this->item->getId(); ?>/<?php echo $this->key; ?>" id="form_edit" method="post">
                            <fieldset>
                            <?php foreach($fields as $field => $content): ?>
                            <?php $required = (!ake('notRequired', $content)) ? 'required' : ''; ?>
                                <?php $label = (ake('label', $content)) ? $content['label'] : ucfirst(\Thin\Inflector::lower($field)); ?>
                                <?php $placeholder = (ake('placeholder', $content)) ? $content['placeholder'] : $label; ?>
                                <?php if (!ake('type', $content)): ?>
                                <?php if (!ake('isTranslated', $content)): ?>
                                <div class="control-group">
                                    <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                    <div class="controls">
                                        <input type="text" value="<?php echo \Thin\Html\Helper::display(htmlentities($this->item->$field)); ?>" <?php echo $required; ?> name="<?php echo $field; ?>" id="<?php echo $field; ?>" placeholder="<?php echo $placeholder; ?>" />
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if (ake('isTranslated', $content)): ?>
                                <?php if (true === $content['isTranslated']): ?>
                                    <div class="control-group">
                                        <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                        <div class="controls">
                                            <ul class="nav nav-tabs">
                                            <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                <li class="<?php if (true === $first): ?>active<?php endif; ?>"><a href="#<?php echo $field; ?>_<?php echo strtolower($lng); ?>" data-toggle="tab"><img src="<?php urlsite(); ?>assets/img/flags/<?php echo strtolower($lng); ?>.png"></a></li>
                                            <?php $first = false; endforeach; ?>
                                            </ul>
                                            <div class="tabbable">
                                                <div class="tab-content">
                                                <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                    <div class="tab-pane<?php if (true === $first): ?> active<?php endif; ?>" id="<?php echo $field; ?>_<?php echo strtolower($lng); ?>">
                                                        <input value="<?php echo \Thin\Html\Helper::display(htmlentities(\Thin\Cms::lng($this->item->$field, $lng))); ?>" type="text" <?php echo $required; ?> name="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" id="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" placeholder="<?php echo $placeholder; ?>" />
                                                    </div>
                                                <?php $first = false; endforeach; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php endif; ?>
                                <?php if (ake('type', $content)): ?>
                                    <?php if ('data' == $content['type']): ?>
                                        <?php
                                        $config =
                                            array(
                                            'entity'    => $content['entity'],
                                            'required'  => (!empty( $required)) ? true : false,
                                            'id'        => $field,
                                            'label'     => $label,
                                            'sort'      => $content['sort'],
                                            'fields'    => $content['fields'],
                                            'value'     => htmlentities($this->item->$field)
                                        );
                                        if (ake('sortOrder', $content)) {
                                            $config['sortOrder'] = $content['sortOrder'];
                                        }
                                        \ThinHelper\Html::formSelectEntity($config);
                                        ?>
                                    <?php endif; ?>
                                    <?php if ('custom' == $content['type']): ?>
                                        <?php echo \Thin\Data::evaluate($content['custom'], $this->item->$field); ?>
                                    <?php endif; ?>
                                    <?php if ('image' == $content['type']): $settings = ake('settings', $content) ? $content['settings'] : array(); ?>
                                        <?php \ThinHelper\Html::formUploadImage($label, $field, false, $this->item->$field, $this->type); ?>
                                    <?php endif; ?>
                                    <?php if ('file' == $content['type']): $settings = ake('settings', $content) ? $content['settings'] : array(); ?>
                                        <?php \ThinHelper\Html::formUploadFile($label, $field, false, $this->item->$field, $this->type); ?>
                                    <?php endif; ?>


                                    <?php if ('code' == $content['type']): ?>
                                    <?php if (!ake('isTranslated', $content)): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <div class="sep"></div>
                                                <input type="hidden" id="<?php echo $field; ?>" name="<?php echo $field; ?>" value="<?php echo str_replace(array('"', "\n", "\r"), array("'", '', ''), $this->item->$field); ?>" />
                                                <pre <?php echo $required; ?> class="thinEditor" id="<?php echo $field; ?>_editor"><?php echo $this->item->$field; ?></pre>
                                            </div>
                                        </div>
                                        <script>
                                            var editor_<?php echo $field; ?> = ace.edit("<?php echo $field; ?>_editor");
                                            editor_<?php echo $field; ?>.setFontSize(22);
                                            editor_<?php echo $field; ?>.setTheme("ace/theme/monokai");
                                            editor_<?php echo $field; ?>.getSession().setMode("ace/mode/php");
                                            $('#form_edit').submit(function(event) {
                                                var contents = editor_<?php echo $field; ?>.getSession().getValue();
                                                $('#<?php echo $field; ?>').val(contents);
                                            });
                                        </script>
                                    <?php endif; ?>
                                    <?php if (ake('isTranslated', $content)): ?>
                                    <?php if (true === $content['isTranslated']): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <ul class="nav nav-tabs">
                                                <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                    <li class="<?php if (true === $first): ?>active<?php endif; ?>"><a href="#<?php echo $field; ?>_<?php echo strtolower($lng); ?>" data-toggle="tab"><img src="<?php urlsite(); ?>assets/img/flags/<?php echo strtolower($lng); ?>.png"></a></li>
                                                <?php $first = false; endforeach; ?>
                                                </ul>
                                                <div class="tabbable">
                                                    <div class="tab-content">
                                                    <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                        <div class="tab-pane<?php if (true === $first): ?> active<?php endif; ?>" id="<?php echo $field; ?>_<?php echo strtolower($lng); ?>">

                                                            <input type="hidden" id="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" name="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" value="<?php echo \Thin\Cms::lng($this->item->$field, $lng); ?>" />
                                                            <pre <?php echo $required; ?> class="thinEditor" id="<?php echo $field; ?>_editor[<?php echo strtolower($lng); ?>]"><?php echo \Thin\Cms::lng($this->item->$field, $lng); ?></pre>
                                                        </div>
                                                        <script>
                                                            var editor_<?php echo $field; ?>_<?php echo $lng; ?> = ace.edit("<?php echo $field; ?>_editor[<?php echo strtolower($lng); ?>]");
                                                            editor_<?php echo $field; ?>_<?php echo $lng; ?>.setFontSize(22);
                                                            editor_<?php echo $field; ?>_<?php echo $lng; ?>.setTheme("ace/theme/monokai");
                                                            editor_<?php echo $field; ?>_<?php echo $lng; ?>.getSession().setMode("ace/mode/php");
                                                            $('#form_edit').submit(function(event) {
                                                                var contents = editor_<?php echo $field; ?>_<?php echo $lng; ?>.getSession().getValue();
                                                                $('#<?php echo $field; ?>[<?php echo strtolower($lng); ?>]').val(contents);

                                                            });
                                                        </script>
                                                    <?php $first = false; endforeach; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php endif; ?>



                                    <?php if ('textarea' == $content['type']): ?>
                                    <?php if (!ake('isTranslated', $content)): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <div class="sep"></div>
                                                <textarea <?php echo $required; ?> style="width: 100%; height: 400px;" name="<?php echo $field; ?>" id="<?php echo $field; ?>" placeholder="<?php echo $placeholder; ?>"><?php echo \Thin\Html\Helper::display($this->item->$field); ?></textarea>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php if (ake('isTranslated', $content)): ?>
                                    <?php if (true === $content['isTranslated']): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <ul class="nav nav-tabs">
                                                <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                    <li class="<?php if (true === $first): ?>active<?php endif; ?>"><a href="#<?php echo $field; ?>_<?php echo strtolower($lng); ?>" data-toggle="tab"><img src="<?php urlsite(); ?>assets/img/flags/<?php echo strtolower($lng); ?>.png"></a></li>
                                                <?php $first = false; endforeach; ?>
                                                </ul>
                                                <div class="tabbable">
                                                    <div class="tab-content">
                                                    <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                        <div class="tab-pane<?php if (true === $first): ?> active<?php endif; ?>" id="<?php echo $field; ?>_<?php echo strtolower($lng); ?>">
                                                            <textarea <?php echo $required; ?> style="width: 100%; height: 400px;" name="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" id="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" placeholder="<?php echo $placeholder; ?>"><?php echo \Thin\Html\Helper::display(\Thin\Cms::lng($this->item->$field, $lng)); ?></textarea>
                                                        </div>
                                                    <?php $first = false; endforeach; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ('editor' == $content['type']): ?>
                                    <?php if (!ake('isTranslated', $content)): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <div class="sep"></div>
                                                <textarea <?php echo $required; ?> class="thinWysiwyg" name="<?php echo $field; ?>" id="<?php echo $field; ?>"><?php echo \Thin\Html\Helper::display($this->item->$field); ?></textarea>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php if (ake('isTranslated', $content)): ?>
                                    <?php if (true === $content['isTranslated']): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <ul class="nav nav-tabs">
                                                <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                    <li class="<?php if (true === $first): ?>active<?php endif; ?>"><a href="#<?php echo $field; ?>_<?php echo strtolower($lng); ?>" data-toggle="tab"><img src="<?php urlsite(); ?>assets/img/flags/<?php echo strtolower($lng); ?>.png"></a></li>
                                                <?php $first = false; endforeach; ?>
                                                </ul>
                                                <div class="tabbable">
                                                    <div class="tab-content">
                                                    <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                        <div class="tab-pane<?php if (true === $first): ?> active<?php endif; ?>" id="<?php echo $field; ?>_<?php echo strtolower($lng); ?>">
                                                            <textarea <?php echo $required; ?> class="thinWysiwyg" name="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" id="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]"><?php echo \Thin\Html\Helper::display(\Thin\Cms::lng($this->item->$field, $lng)); ?></textarea>
                                                        </div>
                                                    <?php $first = false; endforeach; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ('password' == $content['type']): ?>
                                    <div class="control-group">
                                        <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                        <div class="controls">
                                            <input type="password" value="<?php echo \Thin\Html\Helper::display(htmlentities($this->item->$field)); ?>" <?php echo $required; ?> name="<?php echo $field; ?>" id="<?php echo $field; ?>" />
                                        </div>
                                    </div>
                                    <?php endif; ?>

                                    <?php if ('date' == $content['type']): ?>
                                    <?php if (!ake('isTranslated', $content)): ?>
                                    <div class="control-group">
                                        <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                        <div class="controls">
                                            <input class="datepicker" type="text" value="<?php echo \Thin\Html\Helper::display(htmlentities($this->item->$field)); ?>" <?php echo $required; ?> name="<?php echo $field; ?>" id="<?php echo $field; ?>" placeholder="<?php echo $placeholder; ?>" />
                                        </div>
                                    </div>
                                    <?php endif; ?>
                                    <?php if (ake('isTranslated', $content)): ?>
                                    <?php if (true === $content['isTranslated']): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <ul class="nav nav-tabs">
                                                <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                    <li class="<?php if (true === $first): ?>active<?php endif; ?>"><a href="#<?php echo $field; ?>_<?php echo strtolower($lng); ?>" data-toggle="tab"><img src="<?php urlsite(); ?>assets/img/flags/<?php echo strtolower($lng); ?>.png"></a></li>
                                                <?php $first = false; endforeach; ?>
                                                </ul>
                                                <div class="tabbable">
                                                    <div class="tab-content">
                                                    <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                        <div class="tab-pane<?php if (true === $first): ?> active<?php endif; ?>" id="<?php echo $field; ?>_<?php echo strtolower($lng); ?>">
                                                            <input value="<?php echo \Thin\Html\Helper::display(htmlentities(\Thin\Cms::lng($this->item->$field, $lng))); ?>" class="datepicker" type="text" <?php echo $required; ?> name="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" id="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" placeholder="<?php echo $placeholder; ?>" />
                                                        </div>
                                                    <?php $first = false; endforeach; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ('html' == $content['type']): ?>
                                    <?php if (!ake('isTranslated', $content)): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <div class="sep"></div>
                                                <textarea style="width: 100%;" name="<?php echo $field; ?>" id="<?php echo $field; ?>" placeholder="<?php echo $placeholder; ?>"><?php echo \Thin\Html\Helper::display($this->item->$field); ?></textarea>
                                            </div>
                                        </div>
                                        <script>
                                            $(document).ready(function() {
                                                $("#<?php echo $field; ?>").wysibb();
                                            });
                                        </script>
                                    <?php endif; ?>
                                    <?php if (ake('isTranslated', $content)): ?>
                                    <?php if (true === $content['isTranslated']): ?>
                                        <div class="control-group">
                                            <label class="control-label" for="<?php echo $field; ?>"><?php echo $label; ?></label>
                                            <div class="controls">
                                                <ul class="nav nav-tabs">
                                                <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                    <li class="<?php if (true === $first): ?>active<?php endif; ?>"><a href="#<?php echo $field; ?>_<?php echo strtolower($lng); ?>" data-toggle="tab"><img src="<?php urlsite(); ?>assets/img/flags/<?php echo strtolower($lng); ?>.png"></a></li>
                                                <?php $first = false; endforeach; ?>
                                                </ul>
                                                <div class="tabbable">
                                                    <div class="tab-content">
                                                    <?php $first = true; foreach($this->cms_languages as $lng): ?>
                                                        <div class="tab-pane<?php if (true === $first): ?> active<?php endif; ?>" id="<?php echo $field; ?>_<?php echo strtolower($lng); ?>">
                                                            <textarea style="width: 100%;" name="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" id="<?php echo $field; ?>[<?php echo strtolower($lng); ?>]" placeholder="<?php echo $placeholder; ?>"><?php echo \Thin\Html\Helper::display(\Thin\Cms::lng($this->item->$field, $lng)); ?></textarea>
                                                        </div>
                                                        <script>
                                                            $(document).ready(function() {
                                                                $("#<?php echo $field; ?>[<?php echo strtolower($lng); ?>]").wysibb();
                                                            });
                                                        </script>
                                                    <?php $first = false; endforeach; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                                <div>
                                    <div class="controls">
                                        <button type="submit" class="btn btn-primary">Mettre à jour <?php echo \Thin\Html\Helper::adminSingular($this->type); ?></button>
                                        <button type="reset" class="btn btn-danger">Annuler</button>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
<?php includes('partials/footer/classic.phtml'); ?>
