<?php includes('partials/header/classic.phtml'); ?>
<style>
    .liList {
        font-weight: 800;
        color: #2C3E50;
        text-transform: uppercase;
    }
</style>
<!-- Main Content -->
    <div id="content" role="main">
        <p style="height: 40px;"></p>
        <div class="section">
            <div class="container">
                <div class="page-header">
                    <h1>
                        Droits
                    </h1>
                </div>
                <div class="row-fluid">
                    <div class="span1"></div>
                    <div class="span8 alert alert-block alert-danger fade in">
                        <button data-dismiss="alert" class="close" type="button">×</button>
                        <h4 class="alert-heading">Vous ne disposez pas des droits suffisants</h4>
                        <p>Merci de rentrer en contact avec votre administrateur.</p>
                    </div>
                    <div class="span3"></div>
                </div>
            </div>
        </div>
    </div>
<?php includes('partials/footer/classic.phtml'); ?>
