        </div>
        <div id="scrollToTop" class="hidden-xs">
            <i class="fa fa-chevron-up fa-white fa-2x"></i>
        </div>
        <section class="bgDark white contact" id="contact">
            <div class="container">
                <div class="row text-center">
                    <div class="col-md-12">
                        <div class="">
                            contact
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer>
            <div class="container">
                <div class="row text-center">
                    <div class="col-md-4 titleFont upper text-left">
                        &reg; 2012 - <?php echo date('Y'); ?> rue de la vape
                    </div>
                    <div class="col-md-8 titleFont upper socialNetwork">
                        <ul>
                            <li><a href=""><i class="fa fa-twitter white fa-2x"></i></a></li>
                            <li><a href=""><i class="fa fa-facebook white fa-2x"></i></a></li>
                            <li><a href="#contact" onclick="app.goDiv('#contact');"><i class="fa fa-envelope white fa-2x"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/js/bootstrap.min.js"></script>
        <script src="<?php $this->asset('js/hover.js'); ?>"></script>
    </body>
</html>
